name: CI/CD

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: nayeemdevopsg
          password: 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

      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/nayeem098/nginx:latest
            ghcr.io/nayeem098/nginx:${{ github.sha }}
